apiVersion: v1
kind: Pod
metadata:
  name: adguardhome-sync
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: adguardhome-sync
      image: ghcr.io/bakito/adguardhome-sync:latest
      args: ["run"]
      env:
        - name: CRON
          value: "0 */2 * * *"
        - name: CONTINUE_ON_ERROR
          value: "true"
        - name: ORIGIN_URL
          valueFrom:
            secretKeyRef:
              name: adguardhome-sync
              key: origin-url
        - name: ORIGIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: adguardhome-sync
              key: origin-username
        - name: ORIGIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguardhome-sync
              key: origin-password
        - name: ORIGIN_INSECURE_SKIP_VERIFY
          value: "true"
        - name: REPLICA1_URL
          value: "http://127.0.0.1:3000"
        - name: REPLICA1_USERNAME
          valueFrom:
            secretKeyRef:
              name: adguardhome-sync
              key: replica-username
        - name: REPLICA1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguardhome-sync
              key: replica-password
        - name: REPLICA1_AUTO_SETUP
          value: "true"
        - name: API_PORT
          value: "0"
        - name: FEATURES_DHCP_SERVER_CONFIG
          value: "false"
        - name: FEATURES_DHCP_STATIC_LEASES
          value: "false"
