apiVersion: v1
kind: Pod
metadata:
  name: adguardhome
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
    - name: adguardhome
      image: docker.io/adguard/adguardhome:latest
      volumeMounts:
        - name: work
          mountPath: /opt/adguardhome/work
        - name: conf
          mountPath: /opt/adguardhome/conf
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: adguard-work
    - name: conf
      persistentVolumeClaim:
        claimName: adguard-conf
