apiVersion: v1
kind: Secret
metadata:
  name: adguardhome-sync
stringData:
  origin-url: "http://changeme-origin:3000"
  origin-username: "admin"
  origin-password: "change-me"
  replica-username: "admin"
  replica-password: "change-me"
